import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import type { ReactNode } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-5`}>
        <header className="mb-10">
          <nav className="flex gap-3">
            <Link href="/">Home</Link>
            <Link href="/app">App</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
